const countries = [
    { code: "Afghanistan", name: "Afghanistan", flag: "assets/flags/Flag_of_Afghanistan.png" },
    { code: "Albania", name: "Albania", flag: "assets/flags/Flag_of_Albania.png" },
    { code: "Algeria", name: "Algeria", flag: "assets/flags/Flag_of_Algeria.png" },
    { code: "Andorra", name: "Andorra", flag: "assets/flags/Flag_of_Andorra.png" },
    { code: "Angola", name: "Angola", flag: "assets/flags/Flag_of_Angola.png" },
    { code: "Antigua and Barbuda", name: "Antigua and Barbuda", flag: "assets/flags/Flag_of_Antigua_and_Barbuda.png" },
    { code: "Argentina", name: "Argentina", flag: "assets/flags/Flag_of_Argentina.png" },
    { code: "Armenia", name: "Armenia", flag: "assets/flags/Flag_of_Armenia.png" },
    { code: "Australia", name: "Australia", flag: "assets/flags/Flag_of_Australia.png" },
    { code: "Austria", name: "Austria", flag: "assets/flags/Flag_of_Austria.png" },
    { code: "Azerbaijan", name: "Azerbaijan", flag: "assets/flags/Flag_of_Azerbaijan.png" },
    { code: "Bahamas", name: "Bahamas", flag: "assets/flags/Flag_of_Bahamas.png" },
    { code: "Bahrain", name: "Bahrain", flag: "assets/flags/Flag_of_Bahrain.png" },
    { code: "Bangladesh", name: "Bangladesh", flag: "assets/flags/Flag_of_Bangladesh.png" },
    { code: "Barbados", name: "Barbados", flag: "assets/flags/Flag_of_Barbados.png" },
    { code: "Belarus", name: "Belarus", flag: "assets/flags/Flag_of_Belarus.png" },
    { code: "Belgium", name: "Belgium", flag: "assets/flags/Flag_of_Belgium.png" },
    { code: "Belize", name: "Belize", flag: "assets/flags/Flag_of_Belize.png" },
    { code: "Benin", name: "Benin", flag: "assets/flags/Flag_of_Benin.png" },
    { code: "Bhutan", name: "Bhutan", flag: "assets/flags/Flag_of_Bhutan.png" },
    { code: "Bolivia", name: "Bolivia", flag: "assets/flags/Flag_of_Bolivia.png" },
    { code: "Bosnia and Herzegovina", name: "Bosnia and Herzegovina", flag: "assets/flags/Flag_of_Bosnia_and_Herzegovina.png" },
    { code: "Botswana", name: "Botswana", flag: "assets/flags/Flag_of_Botswana.png" },
    { code: "Brazil", name: "Brazil", flag: "assets/flags/Flag_of_Brazil.png" },
    { code: "Brunei", name: "Brunei", flag: "assets/flags/Flag_of_Brunei.png" },
    { code: "Bulgaria", name: "Bulgaria", flag: "assets/flags/Flag_of_Bulgaria.png" },
    { code: "Burkina Faso", name: "Burkina Faso", flag: "assets/flags/Flag_of_Burkina_Faso.png" },
    { code: "Burundi", name: "Burundi", flag: "assets/flags/Flag_of_Burundi.png" },
    { code: "Cambodia", name: "Cambodia", flag: "assets/flags/Flag_of_Cambodia.png" },
    { code: "Cameroon", name: "Cameroon", flag: "assets/flags/Flag_of_Cameroon.png" },
    { code: "Canada", name: "Canada", flag: "assets/flags/Flag_of_Canada.png" },
    { code: "Cape Verde", name: "Cape Verde", flag: "assets/flags/Flag_of_Cape_Verde.png" },
    { code: "Central African Republic", name: "Central African Republic", flag: "assets/flags/Flag_of_Central_African_Republic.png" },
    { code: "Chad", name: "Chad", flag: "assets/flags/Flag_of_Chad.png" },
    { code: "Chile", name: "Chile", flag: "assets/flags/Flag_of_Chile.png" },
    { code: "China", name: "China", flag: "assets/flags/Flag_of_China.png" },
    { code: "Colombia", name: "Colombia", flag: "assets/flags/Flag_of_Colombia.png" },
    { code: "Comoros", name: "Comoros", flag: "assets/flags/Flag_of_the_Comoros.png" },
    { code: "Congo", name: "Congo", flag: "assets/flags/Flag_of_Congo.png" },
    { code: "Costa Rica", name: "Costa Rica", flag: "assets/flags/Flag_of_Costa_Rica.png" },
    { code: "Croatia", name: "Croatia", flag: "assets/flags/Flag_of_Croatia.png" },
    { code: "Cuba", name: "Cuba", flag: "assets/flags/Flag_of_Cuba.png" },
    { code: "Cyprus", name: "Cyprus", flag: "assets/flags/Flag_of_Cyprus.png" },
    { code: "Czechia", name: "Czechia", flag: "assets/flags/Flag_of_the_Czech_Republic.png" },
    { code: "Denmark", name: "Denmark", flag: "assets/flags/Flag_of_Denmark.png" },
    { code: "Djibouti", name: "Djibouti", flag: "assets/flags/Flag_of_Djibouti.png" },
    { code: "Dominica", name: "Dominica", flag: "assets/flags/Flag_of_Dominica.png" },
    { code: "Dominican Republic", name: "Dominican Republic", flag: "assets/flags/Flag_of_the_Dominican_Republic.png" },
    { code: "East Timor", name: "East Timor", flag: "assets/flags/Flag_of_East_Timor.png" },
    { code: "Ecuador", name: "Ecuador", flag: "assets/flags/Flag_of_Ecuador.png" },
    { code: "Egypt", name: "Egypt", flag: "assets/flags/Flag_of_Egypt.png" },
    { code: "El Salvador", name: "El Salvador", flag: "assets/flags/Flag_of_El_Salvador.png" },
    { code: "Equatorial Guinea", name: "Equatorial Guinea", flag: "assets/flags/Flag_of_Equatorial_Guinea.png" },
    { code: "Eritrea", name: "Eritrea", flag: "assets/flags/Flag_of_Eritrea.png" },
    { code: "Estonia", name: "Estonia", flag: "assets/flags/Flag_of_Estonia.png" },
    { code: "Eswatini", name: "Eswatini", flag: "assets/flags/Flag_of_Eswatini.png" },
    { code: "Ethiopia", name: "Ethiopia", flag: "assets/flags/Flag_of_Ethiopia.png" },
    { code: "Fiji", name: "Fiji", flag: "assets/flags/Flag_of_Fiji.png" },
    { code: "Finland", name: "Finland", flag: "assets/flags/Flag_of_Finland.png" },
    { code: "France", name: "France", flag: "assets/flags/Flag_of_France.png" },
    { code: "Gabon", name: "Gabon", flag: "assets/flags/Flag_of_Gabon.png" },
    { code: "Gambia", name: "Gambia", flag: "assets/flags/Flag_of_The_Gambia.png" },
    { code: "Georgia", name: "Georgia", flag: "assets/flags/Flag_of_Georgia.png" },
    { code: "Germany", name: "Germany", flag: "assets/flags/Flag_of_Germany.png" },
    { code: "Ghana", name: "Ghana", flag: "assets/flags/Flag_of_Ghana.png" },
    { code: "Greece", name: "Greece", flag: "assets/flags/Flag_of_Greece.png" },
    { code: "Grenada", name: "Grenada", flag: "assets/flags/Flag_of_Grenada.png" },
    { code: "Guatemala", name: "Guatemala", flag: "assets/flags/Flag_of_Guatemala.png" },
    { code: "Guinea", name: "Guinea", flag: "assets/flags/Flag_of_Guinea.png" },
    { code: "Guinea-Bissau", name: "Guinea-Bissau", flag: "assets/flags/Flag_of_Guinea-Bissau.png" },
    { code: "Guyana", name: "Guyana", flag: "assets/flags/Flag_of_Guyana.png" },
    { code: "Haiti", name: "Haiti", flag: "assets/flags/Flag_of_Haiti.png" },
    { code: "Honduras", name: "Honduras", flag: "assets/flags/Flag_of_Honduras.png" },
    { code: "Hungary", name: "Hungary", flag: "assets/flags/Flag_of_Hungary.png" },
    { code: "Iceland", name: "Iceland", flag: "assets/flags/Flag_of_Iceland.png" },
    { code: "India", name: "India", flag: "assets/flags/Flag_of_India.png" },
    { code: "Indonesia", name: "Indonesia", flag: "assets/flags/Flag_of_Indonesia.png" },
    { code: "Iran", name: "Iran", flag: "assets/flags/Flag_of_Iran.png" },
    { code: "Iraq", name: "Iraq", flag: "assets/flags/Flag_of_Iraq.png" },
    { code: "Ireland", name: "Ireland", flag: "assets/flags/Flag_of_Ireland.png" },
    { code: "Israel", name: "Israel", flag: "assets/flags/Flag_of_Israel.png" },
    { code: "Italy", name: "Italy", flag: "assets/flags/Flag_of_Italy.png" },
    { code: "Ivory Coast", name: "Ivory Coast", flag: "assets/flags/Flag_of_Ivory_Coast.png" },
    { code: "Jamaica", name: "Jamaica", flag: "assets/flags/Flag_of_Jamaica.png" },
    { code: "Japan", name: "Japan", flag: "assets/flags/Flag_of_Japan.png" },
    { code: "Jordan", name: "Jordan", flag: "assets/flags/Flag_of_Jordan.png" },
    { code: "Kazakhstan", name: "Kazakhstan", flag: "assets/flags/Flag_of_Kazakhstan.png" },
    { code: "Kenya", name: "Kenya", flag: "assets/flags/Flag_of_Kenya.png" },
    { code: "Kiribati", name: "Kiribati", flag: "assets/flags/Flag_of_Kiribati.png" },
    { code: "Kuwait", name: "Kuwait", flag: "assets/flags/Flag_of_Kuwait.png" },
    { code: "Kyrgyzstan", name: "Kyrgyzstan", flag: "assets/flags/Flag_of_Kyrgyzstan.png" },
    { code: "Laos", name: "Laos", flag: "assets/flags/Flag_of_Laos.png" },
    { code: "Latvia", name: "Latvia", flag: "assets/flags/Flag_of_Latvia.png" },
    { code: "Lebanon", name: "Lebanon", flag: "assets/flags/Flag_of_Lebanon.png" },
    { code: "Lesotho", name: "Lesotho", flag: "assets/flags/Flag_of_Lesotho.png" },
    { code: "Liberia", name: "Liberia", flag: "assets/flags/Flag_of_Liberia.png" },
    { code: "Libya", name: "Libya", flag: "assets/flags/Flag_of_Libya.png" },
    { code: "Liechtenstein", name: "Liechtenstein", flag: "assets/flags/Flag_of_Liechtenstein.png" },
    { code: "Lithuania", name: "Lithuania", flag: "assets/flags/Flag_of_Lithuania.png" },
    { code: "Luxembourg", name: "Luxembourg", flag: "assets/flags/Flag_of_Luxembourg.png" },
    { code: "Madagascar", name: "Madagascar", flag: "assets/flags/Flag_of_Madagascar.png" },
    { code: "Malawi", name: "Malawi", flag: "assets/flags/Flag_of_Malawi.png" },
    { code: "Malaysia", name: "Malaysia", flag: "assets/flags/Flag_of_Malaysia.png" },
    { code: "Maldives", name: "Maldives", flag: "assets/flags/Flag_of_Maldives.png" },
    { code: "Mali", name: "Mali", flag: "assets/flags/Flag_of_Mali.png" },
    { code: "Malta", name: "Malta", flag: "assets/flags/Flag_of_Malta.png" },
    { code: "Marshall Islands", name: "Marshall Islands", flag: "assets/flags/Flag_of_Marshall_Islands.png" },
    { code: "Mauritania", name: "Mauritania", flag: "assets/flags/Flag_of_Mauritania.png" },
    { code: "Mauritius", name: "Mauritius", flag: "assets/flags/Flag_of_Mauritius.png" },
    { code: "Mexico", name: "Mexico", flag: "assets/flags/Flag_of_Mexico.png" },
    { code: "Micronesia", name: "Micronesia", flag: "assets/flags/Flag_of_Micronesia.png" },
    { code: "Moldova", name: "Moldova", flag: "assets/flags/Flag_of_Moldova.png" },
    { code: "Monaco", name: "Monaco", flag: "assets/flags/Flag_of_Monaco.png" },
    { code: "Mongolia", name: "Mongolia", flag: "assets/flags/Flag_of_Mongolia.png" },
    { code: "Montenegro", name: "Montenegro", flag: "assets/flags/Flag_of_Montenegro.png" },
    { code: "Morocco", name: "Morocco", flag: "assets/flags/Flag_of_Morocco.png" },
    { code: "Mozambique", name: "Mozambique", flag: "assets/flags/Flag_of_Mozambique.png" },
    { code: "Myanmar", name: "Myanmar", flag: "assets/flags/Flag_of_Myanmar.png" },
    { code: "Namibia", name: "Namibia", flag: "assets/flags/Flag_of_Namibia.png" },
    { code: "Nauru", name: "Nauru", flag: "assets/flags/Flag_of_Nauru.png" },
    { code: "Nepal", name: "Nepal", flag: "assets/flags/Flag_of_Nepal.png" },
    { code: "Netherlands", name: "Netherlands", flag: "assets/flags/Flag_of_Netherlands.png" },
    { code: "New Zealand", name: "New Zealand", flag: "assets/flags/Flag_of_New_Zealand.png" },
    { code: "Nicaragua", name: "Nicaragua", flag: "assets/flags/Flag_of_Nicaragua.png" },
    { code: "Niger", name: "Niger", flag: "assets/flags/Flag_of_Niger.png" },
    { code: "Nigeria", name: "Nigeria", flag: "assets/flags/Flag_of_Nigeria.png" },
    { code: "North Korea", name: "North Korea", flag: "assets/flags/Flag_of_North_Korea.png" },
    { code: "North Macedonia", name: "North Macedonia", flag: "assets/flags/Flag_of_North_Macedonia.png" },
    { code: "Norway", name: "Norway", flag: "assets/flags/Flag_of_Norway.png" },
    { code: "Oman", name: "Oman", flag: "assets/flags/Flag_of_Oman.png" },
    { code: "Pakistan", name: "Pakistan", flag: "assets/flags/Flag_of_Pakistan.png" },
    { code: "Palau", name: "Palau", flag: "assets/flags/Flag_of_Palau.png" },
    { code: "Palestine", name: "Palestine", flag: "assets/flags/Flag_of_Palestine.png" },
    { code: "Panama", name: "Panama", flag: "assets/flags/Flag_of_Panama.png" },
    { code: "Papua New Guinea", name: "Papua New Guinea", flag: "assets/flags/Flag_of_Papua_New_Guinea.png" },
    { code: "Paraguay", name: "Paraguay", flag: "assets/flags/Flag_of_Paraguay.png" },
    { code: "Peru", name: "Peru", flag: "assets/flags/Flag_of_Peru.png" },
    { code: "Philippines", name: "Philippines", flag: "assets/flags/Flag_of_Philippines.png" },
    { code: "Poland", name: "Poland", flag: "assets/flags/Flag_of_Poland.png" },
    { code: "Portugal", name: "Portugal", flag: "assets/flags/Flag_of_Portugal.png" },
    { code: "Qatar", name: "Qatar", flag: "assets/flags/Flag_of_Qatar.png" },
    { code: "Romania", name: "Romania", flag: "assets/flags/Flag_of_Romania.png" },
    { code: "Russia", name: "Russia", flag: "assets/flags/Flag_of_Russia.png" },
    { code: "Rwanda", name: "Rwanda", flag: "assets/flags/Flag_of_Rwanda.png" },
    { code: "Saint Kitts and Nevis", name: "Saint Kitts and Nevis", flag: "assets/flags/Flag_of_Saint_Kitts_and_Nevis.png" },
    { code: "Saint Lucia", name: "Saint Lucia", flag: "assets/flags/Flag_of_Saint_Lucia.png" },
    { code: "Saint Vincent and the Grenadines", name: "Saint Vincent and the Grenadines", flag: "assets/flags/Flag_of_Saint_Vincent_and_the_Grenadines.png" },
    { code: "Samoa", name: "Samoa", flag: "assets/flags/Flag_of_Samoa.png" },
    { code: "San Marino", name: "San Marino", flag: "assets/flags/Flag_of_San_Marino.png" },
    { code: "Saudi Arabia", name: "Saudi Arabia", flag: "assets/flags/Flag_of_Saudi_Arabia.png" },
    { code: "São Tomé and Príncipe", name: "São Tomé and Príncipe", flag: "assets/flags/Flag_of_São_Tomé_and_Príncipe.png" },
    { code: "Senegal", name: "Senegal", flag: "assets/flags/Flag_of_Senegal.png" },
    { code: "Serbia", name: "Serbia", flag: "assets/flags/Flag_of_Serbia.png" },
    { code: "Seychelles", name: "Seychelles", flag: "assets/flags/Flag_of_Seychelles.png" },
    { code: "Sierra Leone", name: "Sierra Leone", flag: "assets/flags/Flag_of_Sierra_Leone.png" },
    { code: "Singapore", name: "Singapore", flag: "assets/flags/Flag_of_Singapore.png" },
    { code: "Slovakia", name: "Slovakia", flag: "assets/flags/Flag_of_Slovakia.png" },
    { code: "Slovenia", name: "Slovenia", flag: "assets/flags/Flag_of_Slovenia.png" },
    { code: "Solomon Islands", name: "Solomon Islands", flag: "assets/flags/Flag_of_Solomon_Islands.png" },
    { code: "Somalia", name: "Somalia", flag: "assets/flags/Flag_of_Somalia.png" },
    { code: "South Africa", name: "South Africa", flag: "assets/flags/Flag_of_South_Africa.png" },
    { code: "South Korea", name: "South Korea", flag: "assets/flags/Flag_of_South_Korea.png" },
    { code: "South Sudan", name: "South Sudan", flag: "assets/flags/Flag_of_South_Sudan.png" },
    { code: "Spain", name: "Spain", flag: "assets/flags/Flag_of_Spain.png" },
    { code: "Sri Lanka", name: "Sri Lanka", flag: "assets/flags/Flag_of_Sri_Lanka.png" },
    { code: "Sudan", name: "Sudan", flag: "assets/flags/Flag_of_Sudan.png" },
    { code: "Suriname", name: "Suriname", flag: "assets/flags/Flag_of_Suriname.png" },
    { code: "Sweden", name: "Sweden", flag: "assets/flags/Flag_of_Sweden.png" },
    { code: "Switzerland", name: "Switzerland", flag: "assets/flags/Flag_of_Switzerland.png" },
    { code: "Syria", name: "Syria", flag: "assets/flags/Flag_of_Syria.png" },
    { code: "Tajikistan", name: "Tajikistan", flag: "assets/flags/Flag_of_Tajikistan.png" },
    { code: "Tanzania", name: "Tanzania", flag: "assets/flags/Flag_of_Tanzania.png" },
    { code: "Thailand", name: "Thailand", flag: "assets/flags/Flag_of_Thailand.png" },
    //{ code: "Timor-Leste", name: "Timor-Leste", flag: "assets/flags/Flag_of_Timor-Leste.png" },
    { code: "Togo", name: "Togo", flag: "assets/flags/Flag_of_Togo.png" },
    { code: "Tonga", name: "Tonga", flag: "assets/flags/Flag_of_Tonga.png" },
    { code: "Trinidad and Tobago", name: "Trinidad and Tobago", flag: "assets/flags/Flag_of_Trinidad_and_Tobago.png" },
    { code: "Tunisia", name: "Tunisia", flag: "assets/flags/Flag_of_Tunisia.png" },
    { code: "Turkey", name: "Turkey", flag: "assets/flags/Flag_of_Turkey.png" },
    { code: "Turkmenistan", name: "Turkmenistan", flag: "assets/flags/Flag_of_Turkmenistan.png" },
    { code: "Tuvalu", name: "Tuvalu", flag: "assets/flags/Flag_of_Tuvalu.png" },
    { code: "Uganda", name: "Uganda", flag: "assets/flags/Flag_of_Uganda.png" },
    { code: "Ukraine", name: "Ukraine", flag: "assets/flags/Flag_of_Ukraine.png" },
    { code: "United Arab Emirates", name: "United Arab Emirates", flag: "assets/flags/Flag_of_United_Arab_Emirates.png" },
    { code: "United Kingdom", name: "United Kingdom", flag: "assets/flags/Flag_of_United_Kingdom.png" },
    { code: "United States", name: "United States", flag: "assets/flags/Flag_of_United_States.png" },
    { code: "Uruguay", name: "Uruguay", flag: "assets/flags/Flag_of_Uruguay.png" },
    { code: "Uzbekistan", name: "Uzbekistan", flag: "assets/flags/Flag_of_Uzbekistan.png" },
    { code: "Vanuatu", name: "Vanuatu", flag: "assets/flags/Flag_of_Vanuatu.png" },
    { code: "Vatican City", name: "Vatican City", flag: "assets/flags/Flag_of_Vatican_City.png" },
    { code: "Venezuela", name: "Venezuela", flag: "assets/flags/Flag_of_Venezuela.png" },
    { code: "Vietnam", name: "Vietnam", flag: "assets/flags/Flag_of_Vietnam.png" },
    { code: "Yemen", name: "Yemen", flag: "assets/flags/Flag_of_Yemen.png" },
    { code: "Zambia", name: "Zambia", flag: "assets/flags/Flag_of_Zambia.png" },
    { code: "Zimbabwe", name: "Zimbabwe", flag: "assets/flags/Flag_of_Zimbabwe.png" }
];

export default countries;
